name: Java-workflow

on: 
  push:
    branches:
      - main

jobs: 
  build:
    name: my-spc
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4
        
      #- name: build Java with maven
      #S  run: mvn package
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar